import { beforeEach, describe, expect, it, vi } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { SWRConfig } from 'swr';
import type { Case } from '@/lib/api';

const api = vi.hoisted(() => ({
  get: vi.fn(), update: vi.fn(), addComment: vi.fn(), addTask: vi.fn(), updateTask: vi.fn(), investigate: vi.fn(), getInvestigation: vi.fn(), openAutoSummaryHtml: vi.fn(),
}));
const toastFn = vi.hoisted(() => vi.fn());
const toastError = vi.hoisted(() => vi.fn());
const toastSuccess = vi.hoisted(() => vi.fn());

vi.mock('@/lib/api', () => ({ __esModule: true, casesApi: api, graphApi: {}, realtimeApi: {} }));
vi.mock('next/navigation', () => ({ useSearchParams: () => new URLSearchParams() }));
vi.mock('./InvestigationLedger', () => ({ InvestigationLedger: () => null }));
vi.mock('@/components/copilot/ContextualActions', () => ({ ContextualActions: () => null }));
vi.mock('@/lib/auth-session', () => ({ authFetch: vi.fn() }));
vi.mock('react-hot-toast', () => ({ __esModule: true, default: Object.assign(toastFn, { error: toastError, success: toastSuccess }) }));

import { CaseWorkspace } from './CaseWorkspace';

// This page used to hide failures behind sample data and false success:
//   - a failed case load showed an INVENTED case ("Suspected lateral movement from finance subnet", assigned to sasha.lin@example.com) under "Demo data";
//   - a failed investigation marked itself completed with invented IOCs (192.168.1.105, c2.evil-corp.io), invented actions ("Isolate WIN-FIN-DB01") and a
//     written-up incident report "Generated by AiSOC AI Investigator (demo mode)";
//   - a failed status change, comment or task kept the change on screen and said "Saved locally (writes disabled in demo)", so after a refresh the work was gone.
const INVENTED = ['Suspected lateral movement from finance subnet', 'sasha.lin@example.com', 'Isolate WIN-FIN-DB01', 'Rotate svc_backup credentials', 'Forensic image of BACKUP-SRV-12', 'Demo data', 'writes disabled'];
const FABRICATED_INVESTIGATION = ['192.168.1.105', 'c2.evil-corp.io', 'Isolate WIN-FIN-DB01', 'Generated by AiSOC AI Investigator', 'ReconAgent'];

const stamp = '2026-10-07T12:00:00Z';
const realCase: Case = {
  id: 'case-1', caseNumber: 'INC-001', title: 'Real phishing case', status: 'open', severity: 'high', createdAt: stamp, updatedAt: stamp, assignee: 'alice@liveoak.test', timeline: [],
  tasks: [{ id: 't1', title: 'Reset the affected password', status: 'todo', createdAt: stamp }],
};

function renderCase() {
  return render(
    <SWRConfig value={{ provider: () => new Map(), dedupingInterval: 0, shouldRetryOnError: false }}>
      <CaseWorkspace caseId="case-1" />
    </SWRConfig>,
  );
}

beforeEach(() => {
  Object.values(api).forEach((m) => m.mockReset());
  [toastFn, toastError, toastSuccess].forEach((m) => m.mockReset());
  api.get.mockResolvedValue(realCase);
});

describe('loading the case', () => {
  it('shows the real case, with no demo badge', async () => {
    const { container } = renderCase();
    expect(await screen.findByText('Real phishing case')).toBeInTheDocument();
    for (const invented of INVENTED) expect(container.textContent).not.toContain(invented);
  });

  it('shows an error with a Retry and a way back, and NO invented case, when the load fails', async () => {
    api.get.mockRejectedValueOnce(new Error('404 case not found'));
    const { container } = renderCase();
    expect(await screen.findByText("Couldn't load case")).toBeInTheDocument();
    expect(screen.getByText(/404 case not found/)).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'Back to cases' })).toBeInTheDocument();
    for (const invented of INVENTED) expect(container.textContent).not.toContain(invented);
    expect(screen.queryByText('Real phishing case')).not.toBeInTheDocument();

    await userEvent.setup().click(screen.getByRole('button', { name: /retry|try again/i }));
    expect(await screen.findByText('Real phishing case')).toBeInTheDocument();
  });
});

describe('changing the status', () => {
  it('says so, and puts the real status back, when the save fails', async () => {
    api.update.mockRejectedValue(new Error('403 forbidden'));
    renderCase();
    await screen.findByText('Real phishing case');
    const select = screen.getByDisplayValue('Open') as HTMLSelectElement;
    await userEvent.setup().selectOptions(select, 'resolved');

    await waitFor(() => expect(toastError).toHaveBeenCalledWith('Could not set status to Resolved: 403 forbidden'));
    await waitFor(() => expect(select.value).toBe('open')); // what the server has, not what was clicked
    expect(api.get.mock.calls.length).toBeGreaterThanOrEqual(2); // it re-read the case
    expect(toastFn).not.toHaveBeenCalled(); // not the old "set locally (writes disabled)" message
    expect(toastSuccess).not.toHaveBeenCalled();
  });

  it('confirms a status change that really saved', async () => {
    api.update.mockResolvedValue({});
    renderCase();
    await screen.findByText('Real phishing case');
    await userEvent.setup().selectOptions(screen.getByDisplayValue('Open'), 'resolved');
    await waitFor(() => expect(toastSuccess).toHaveBeenCalledWith('Status set to Resolved'));
    expect(api.update).toHaveBeenCalledWith('case-1', { status: 'resolved' });
    expect(toastError).not.toHaveBeenCalled();
  });
});

describe('adding a comment', () => {
  const box = () => screen.getByPlaceholderText('Drop your findings, IOCs, or next steps…') as HTMLTextAreaElement;

  it('says so, removes the comment it showed, and gives the text back, when the save fails', async () => {
    api.addComment.mockRejectedValue(new Error('500 server error'));
    renderCase();
    await screen.findByText('Real phishing case');
    const user = userEvent.setup();
    await user.type(box(), 'Found the sender in the mail logs');
    await user.click(screen.getByRole('button', { name: 'Post' }));

    await waitFor(() => expect(toastError).toHaveBeenCalledWith('Could not add the comment: 500 server error'));
    await waitFor(() => expect(box().value).toBe('Found the sender in the mail logs')); // not lost
    // ...and not left in the timeline as if saved. (A controlled <textarea> keeps its text as content, so the box itself would match a plain text query.)
    expect(screen.queryAllByText('Found the sender in the mail logs').filter((el) => el.tagName !== 'TEXTAREA')).toEqual([])
    expect(toastFn).not.toHaveBeenCalled();
    expect(toastSuccess).not.toHaveBeenCalled();
  });

  it('confirms a comment that really saved', async () => {
    api.addComment.mockResolvedValue({});
    renderCase();
    await screen.findByText('Real phishing case');
    const user = userEvent.setup();
    await user.type(box(), 'Looks benign');
    await user.click(screen.getByRole('button', { name: 'Post' }));
    await waitFor(() => expect(toastSuccess).toHaveBeenCalledWith('Comment added'));
    expect(api.addComment).toHaveBeenCalledWith('case-1', 'Looks benign');
    expect(box().value).toBe('');
  });
});

describe('tasks', () => {
  it('says so, drops the task it showed, and keeps the text, when adding fails', async () => {
    api.addTask.mockRejectedValue(new Error('500 server error'));
    renderCase();
    await screen.findByText('Real phishing case');
    const user = userEvent.setup();
    const input = screen.getByPlaceholderText('Add task and press ↵') as HTMLInputElement;
    await user.type(input, 'Block the sender domain');
    await user.click(screen.getByRole('button', { name: 'Add' }));

    await waitFor(() => expect(toastError).toHaveBeenCalledWith('Could not add the task: 500 server error'));
    await waitFor(() => expect(input.value).toBe('Block the sender domain'));
    expect(screen.queryByText('Block the sender domain')).not.toBeInTheDocument();
    expect(toastFn).not.toHaveBeenCalled();
  });

  it('says so, and puts the real task status back, when changing it fails', async () => {
    api.updateTask.mockRejectedValue(new Error('500 server error'));
    renderCase();
    await screen.findByText('Reset the affected password');
    await userEvent.setup().click(screen.getByRole('button', { name: 'Mark task in_progress' }));

    await waitFor(() => expect(toastError).toHaveBeenCalledWith('Could not update the task: 500 server error'));
    // the optimistic change would have turned the button into "Mark task done"; the server still has it as todo
    await waitFor(() => expect(screen.getByRole('button', { name: 'Mark task in_progress' })).toBeInTheDocument());
    expect(screen.queryByRole('button', { name: 'Mark task done' })).not.toBeInTheDocument();
  });
});

describe('investigating with the agent', () => {
  it('says it failed, and fabricates NO investigation or report, when it cannot start', async () => {
    api.investigate.mockRejectedValue(new Error('agents unreachable'));
    const { container } = renderCase();
    await screen.findByText('Real phishing case');
    await userEvent.setup().click(screen.getByRole('button', { name: 'Investigate with agent' }));

    await waitFor(() => expect(toastError).toHaveBeenCalledWith('Could not start the investigation: agents unreachable'));
    for (const fabricated of FABRICATED_INVESTIGATION) expect(container.textContent).not.toContain(fabricated);
    expect(toastFn).not.toHaveBeenCalled(); // not "Demo mode: investigation not available"
    expect(toastSuccess).not.toHaveBeenCalled();
    // and it is not stuck "Investigating…"
    await waitFor(() => expect(screen.getByRole('button', { name: 'Investigate with agent' })).toBeEnabled());
  });
});
