import { beforeEach, describe, expect, it, vi } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';

const authFetch = vi.hoisted(() => vi.fn());
vi.mock('@/lib/auth-session', () => ({ authFetch }));
const confirmAction = vi.hoisted(() => vi.fn());
vi.mock('@/lib/api', async (importOriginal) => ({ ...(await importOriginal<typeof import('@/lib/api')>()), copilotApi: { confirmAction } }));

import InvestigationChat from './InvestigationChat';

// This component carried a hard-coded case ("CS-2187", 7 alerts, 3 IOCs, risk "High"): shown in its panel, and the case id was sent to the copilot as the context of EVERY message. Closing an
// investigation WITHOUT a run built a local "summary" from those invented figures, signed it "Generated by AiSOC - beenu@cyble.com" (a person's address), gave it a made-up artifact id, and announced
// "Summary generated and stored as an artifact" when nothing had been stored. A failed chat call was shown as an assistant message.
const json = (status: number, body: unknown) => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
const INVENTED = ['CS-2187', 'beenu@cyble.com', 'Generated by AiSOC', 'demo-'];

let chatResponse: () => Promise<Response>;
let closeResponse: () => Promise<Response>;

beforeEach(() => {
  authFetch.mockReset();
  chatResponse = async () => json(200, { reply: { content: 'The sender domain was registered yesterday.' } });
  closeResponse = async () => json(200, { artifact_id: 'art-123', summary_markdown: '# Server-generated summary' });
  authFetch.mockImplementation(async (url: string) => (url.includes('/close') ? closeResponse() : url.includes('/copilot/chat') ? chatResponse() : json(404, {})));
});

const composer = () => screen.getByPlaceholderText(/Ask about an alert, IOC, or investigation/);
async function ask(text: string) {
  const user = userEvent.setup();
  await user.type(composer(), text);
  await user.click(screen.getByRole('button', { name: 'Send' }));
}
async function closeInvestigation() {
  const user = userEvent.setup();
  await user.click(screen.getByRole('button', { name: 'Close Investigation' }));
  await user.click(screen.getByRole('button', { name: 'Confirm Close' }));
}
const chatBody = () => JSON.parse(authFetch.mock.calls.find((c) => String(c[0]).includes('/copilot/chat'))![1].body);

describe('the context panel', () => {
  it('shows a dash for everything it was not given, and no invented case', () => {
    const { container } = render(<InvestigationChat />);
    expect(screen.getAllByText('\u2014')).toHaveLength(4); // case id, alert count, IOCs, risk level
    for (const invented of INVENTED) expect(container.textContent).not.toContain(invented);
    expect(container.textContent).not.toMatch(/\bHigh\b/);
  });

  it('shows the real case it was given', () => {
    render(<InvestigationChat caseId="INC-9" alertCount={4} iocsFound={2} riskLevel="Low" />);
    expect(screen.getByText('INC-9')).toBeInTheDocument();
    expect(screen.getByText('4')).toBeInTheDocument();
    expect(screen.getByText('2')).toBeInTheDocument();
    expect(screen.getByText('Low')).toBeInTheDocument();
    expect(screen.queryByText('\u2014')).not.toBeInTheDocument();
  });
});

describe('what the copilot is told', () => {
  it('names no case when none was given', async () => {
    render(<InvestigationChat />);
    await ask('Is this IP bad?');
    await screen.findByText('The sender domain was registered yesterday.');
    expect(chatBody().context.caseId).toBeUndefined();
    expect(JSON.stringify(chatBody())).not.toContain('CS-2187');
    expect(chatBody().context.page).toBe('investigation');
  });

  it('passes the real case and run when it has them', async () => {
    render(<InvestigationChat runId="run-1" caseId="INC-9" />);
    await ask('Summarise');
    await screen.findByText('The sender domain was registered yesterday.');
    expect(chatBody().context).toMatchObject({ caseId: 'INC-9', runId: 'run-1', page: 'investigation' });
  });
});

describe('when the copilot cannot answer', () => {
  it('shows the server\'s reason as a notice, and does not count it as an AI response', async () => {
    chatResponse = async () => json(503, { detail: 'The copilot cannot answer right now: no language-model API key is configured for the copilot.' });
    render(<InvestigationChat />);
    await ask('Anything?');
    expect(await screen.findByText(/The copilot could not answer: The copilot cannot answer right now: no language-model API key/)).toBeInTheDocument();
    expect(screen.getByText('0 AI responses')).toBeInTheDocument();
  });

  it('says so when the network fails', async () => {
    chatResponse = async () => {
      throw new Error('network down');
    };
    render(<InvestigationChat />);
    await ask('Anything?');
    expect(await screen.findByText('The copilot could not answer: network down')).toBeInTheDocument();
    expect(screen.getByText('0 AI responses')).toBeInTheDocument();
  });

  it('says so when a 200 carries no reply', async () => {
    chatResponse = async () => json(200, {});
    render(<InvestigationChat />);
    await ask('Anything?');
    expect(await screen.findByText('The copilot could not answer: it returned an empty reply')).toBeInTheDocument();
  });

  it('counts a real reply as an AI response', async () => {
    render(<InvestigationChat />);
    await ask('Anything?');
    await screen.findByText('The sender domain was registered yesterday.');
    expect(screen.getByText('1 AI responses')).toBeInTheDocument();
  });
});

describe('closing the investigation', () => {
  it('without a run, says there is nothing to close and fabricates no summary', async () => {
    const { container } = render(<InvestigationChat />);
    await closeInvestigation();
    expect(await screen.findByText('There is no investigation run attached to this chat, so there is nothing to close.')).toBeInTheDocument();
    expect(screen.queryByText('Investigation Summary')).not.toBeInTheDocument();
    expect(screen.queryByText(/Artifact ID/)).not.toBeInTheDocument();
    expect(authFetch.mock.calls.some((c) => String(c[0]).includes('/close'))).toBe(false);
    expect(container.textContent).not.toMatch(/Closed/);
    for (const invented of INVENTED) expect(container.textContent).not.toContain(invented);
    expect(container.textContent).not.toContain('stored as an artifact');
  });

  it('with a run, closes it through the API and shows what the server produced', async () => {
    render(<InvestigationChat runId="run-1" />);
    await closeInvestigation();
    expect(await screen.findByText('Investigation Summary')).toBeInTheDocument();
    expect(screen.getByText('art-123')).toBeInTheDocument();
    const call = authFetch.mock.calls.find((c) => String(c[0]).includes('/close'))!;
    expect(call[0]).toBe('/api/v1/investigations/run-1/close');
    expect(JSON.parse(call[1].body)).toEqual({ analyst_note: null });
  });

  it('says so, and stays open, when the server refuses', async () => {
    closeResponse = async () => new Response('nope', { status: 500 });
    render(<InvestigationChat runId="run-1" />);
    await closeInvestigation();
    expect(await screen.findByText(/Failed to close investigation: Error: Close failed: 500 nope/)).toBeInTheDocument();
    await waitFor(() => expect(screen.queryByText('Investigation Summary')).not.toBeInTheDocument());
    // still open, and the confirm step is still there to retry
    expect(screen.getByRole('button', { name: 'Confirm Close' })).toBeEnabled();
    expect(screen.queryByText(/Artifact ID/)).not.toBeInTheDocument();
  });
});

describe('when the copilot asks to delete something', () => {
  const pending = { action: 'delete_alert', summary: 'Permanently delete alert "Beaconing host"? This cannot be undone.', token: 'tok-inv', expiresAt: Math.floor(Date.now() / 1000) + 300 };

  beforeEach(() => {
    confirmAction.mockReset();
    chatResponse = async () => json(200, { reply: { content: 'I have asked you to confirm the deletion.' }, pendingActions: [pending] });
  });

  it('shows a confirmation prompt under the reply and has deleted nothing yet', async () => {
    render(<InvestigationChat />);
    await ask('delete that alert');
    expect(await screen.findByRole('group', { name: 'Confirmation required' })).toBeInTheDocument();
    expect(screen.getByText(/Permanently delete alert "Beaconing host"/)).toBeInTheDocument();
    expect(confirmAction).not.toHaveBeenCalled();
  });

  it("deletes only when the analyst clicks, with that prompt's own token", async () => {
    confirmAction.mockResolvedValue({ status: 'done', action: 'delete_alert', result: { deleted: true } });
    render(<InvestigationChat />);
    await ask('delete that alert');
    await userEvent.setup().click(await screen.findByRole('button', { name: 'Delete' }));
    expect(await screen.findByText('Deleted.')).toBeInTheDocument();
    expect(confirmAction).toHaveBeenCalledTimes(1);
    expect(confirmAction).toHaveBeenCalledWith('tok-inv');
  });

  it('shows no prompt for an ordinary reply', async () => {
    chatResponse = async () => json(200, { reply: { content: 'The sender domain was registered yesterday.' } });
    render(<InvestigationChat />);
    await ask('what is this domain?');
    expect(await screen.findByText('The sender domain was registered yesterday.')).toBeInTheDocument();
    expect(screen.queryByRole('group', { name: 'Confirmation required' })).not.toBeInTheDocument();
  });
});
